//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectPlay.TicketPlay.UI.Native.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectPlay.TicketPlay.UI.Native.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket &amp; Play.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.connect-en-play.nl.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:7284.
        /// </summary>
        internal static string Development_BaseUrl {
            get {
                return ResourceManager.GetString("Development_BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        internal static string Genre_Drama {
            get {
                return ResourceManager.GetString("Genre_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Genre_Family {
            get {
                return ResourceManager.GetString("Genre_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science-fiction.
        /// </summary>
        internal static string Genre_ScienceFiction {
            get {
                return ResourceManager.GetString("Genre_ScienceFiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        internal static string Genre_Thriller {
            get {
                return ResourceManager.GetString("Genre_Thriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now in cinema.
        /// </summary>
        internal static string Home_Current {
            get {
                return ResourceManager.GetString("Home_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to see?.
        /// </summary>
        internal static string Home_Header {
            get {
                return ResourceManager.GetString("Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Action {
            get {
                return ResourceManager.GetString("Login_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log in. Check your credentials and try again..
        /// </summary>
        internal static string Login_Fail {
            get {
                return ResourceManager.GetString("Login_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string Movie_SeeMore {
            get {
                return ResourceManager.GetString("Movie_SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MovieDetail_BackButton {
            get {
                return ResourceManager.GetString("MovieDetail_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall {0}.
        /// </summary>
        internal static string MovieDetail_HallHeader {
            get {
                return ResourceManager.GetString("MovieDetail_HallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To tickets.
        /// </summary>
        internal static string MovieDetail_NextButton {
            get {
                return ResourceManager.GetString("MovieDetail_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no screenings for this film..
        /// </summary>
        internal static string MovieDetail_NoScreenings {
            get {
                return ResourceManager.GetString("MovieDetail_NoScreenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film not found :(.
        /// </summary>
        internal static string MovieDetail_NotFound {
            get {
                return ResourceManager.GetString("MovieDetail_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenings.
        /// </summary>
        internal static string MovieDetail_ScreeningsHeader {
            get {
                return ResourceManager.GetString("MovieDetail_ScreeningsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mystery movie! The full details will be revealed on the day of the screening..
        /// </summary>
        internal static string MovieDetail_SneakPreviewDescription {
            get {
                return ResourceManager.GetString("MovieDetail_SneakPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneak preview.
        /// </summary>
        internal static string MovieDetail_SneakPreviewTitle {
            get {
                return ResourceManager.GetString("MovieDetail_SneakPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In hall {0} at {1:HHmm}.
        /// </summary>
        internal static string OrderOverview_Location {
            get {
                return ResourceManager.GetString("OrderOverview_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order overview.
        /// </summary>
        internal static string OrderOverview_Title {
            get {
                return ResourceManager.GetString("OrderOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string SeatModal_LegendAvailable {
            get {
                return ResourceManager.GetString("SeatModal_LegendAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        internal static string SeatModal_LegendOccupied {
            get {
                return ResourceManager.GetString("SeatModal_LegendOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string SeatModal_LegendReserved {
            get {
                return ResourceManager.GetString("SeatModal_LegendReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string SeatModal_LegendSelected {
            get {
                return ResourceManager.GetString("SeatModal_LegendSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string SeatModal_Row {
            get {
                return ResourceManager.GetString("SeatModal_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        internal static string SeatModal_Screen {
            get {
                return ResourceManager.GetString("SeatModal_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat.
        /// </summary>
        internal static string SeatModal_Seat {
            get {
                return ResourceManager.GetString("SeatModal_Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seats chosen.
        /// </summary>
        internal static string SeatModal_SummaryEmpty {
            get {
                return ResourceManager.GetString("SeatModal_SummaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected seats.
        /// </summary>
        internal static string SeatModal_SummaryTitle {
            get {
                return ResourceManager.GetString("SeatModal_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheelchair.
        /// </summary>
        internal static string SeatModal_Wheelchair {
            get {
                return ResourceManager.GetString("SeatModal_Wheelchair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Tickets_Header {
            get {
                return ResourceManager.GetString("Tickets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall {0} at {1}.
        /// </summary>
        internal static string Tickets_ScreeningLocation {
            get {
                return ResourceManager.GetString("Tickets_ScreeningLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings.
        /// </summary>
        internal static string You_Header {
            get {
                return ResourceManager.GetString("You_Header", resourceCulture);
            }
        }
    }
}
