//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectPlay.TicketPlay.UI.Native.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectPlay.TicketPlay.UI.Native.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket &amp; Play.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an arrangement here, and we&apos;ll get it to your seat before the movie starts!.
        /// </summary>
        internal static string Arrangements_Description {
            get {
                return ResourceManager.GetString("Arrangements_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string Arrangements_Drinks {
            get {
                return ResourceManager.GetString("Arrangements_Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snacks.
        /// </summary>
        internal static string Arrangements_Snacks {
            get {
                return ResourceManager.GetString("Arrangements_Snacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        internal static string Arrangements_Specials {
            get {
                return ResourceManager.GetString("Arrangements_Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrangements.
        /// </summary>
        internal static string Arrangements_Title {
            get {
                return ResourceManager.GetString("Arrangements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.connect-en-play.nl.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:7284.
        /// </summary>
        internal static string Development_BaseUrl {
            get {
                return ResourceManager.GetString("Development_BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        internal static string Genre_Drama {
            get {
                return ResourceManager.GetString("Genre_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Genre_Family {
            get {
                return ResourceManager.GetString("Genre_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science-fiction.
        /// </summary>
        internal static string Genre_ScienceFiction {
            get {
                return ResourceManager.GetString("Genre_ScienceFiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        internal static string Genre_Thriller {
            get {
                return ResourceManager.GetString("Genre_Thriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now in cinema.
        /// </summary>
        internal static string Home_Current {
            get {
                return ResourceManager.GetString("Home_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to see?.
        /// </summary>
        internal static string Home_Header {
            get {
                return ResourceManager.GetString("Home_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Action {
            get {
                return ResourceManager.GetString("Login_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to log in. Check your credentials and try again..
        /// </summary>
        internal static string Login_Fail {
            get {
                return ResourceManager.GetString("Login_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string Movie_SeeMore {
            get {
                return ResourceManager.GetString("Movie_SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MovieDetail_BackButton {
            get {
                return ResourceManager.GetString("MovieDetail_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall {0}.
        /// </summary>
        internal static string MovieDetail_HallHeader {
            get {
                return ResourceManager.GetString("MovieDetail_HallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To tickets.
        /// </summary>
        internal static string MovieDetail_NextButton {
            get {
                return ResourceManager.GetString("MovieDetail_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no screenings for this film..
        /// </summary>
        internal static string MovieDetail_NoScreenings {
            get {
                return ResourceManager.GetString("MovieDetail_NoScreenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film not found :(.
        /// </summary>
        internal static string MovieDetail_NotFound {
            get {
                return ResourceManager.GetString("MovieDetail_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenings.
        /// </summary>
        internal static string MovieDetail_ScreeningsHeader {
            get {
                return ResourceManager.GetString("MovieDetail_ScreeningsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mystery movie! The full details will be revealed on the day of the screening..
        /// </summary>
        internal static string MovieDetail_SneakPreviewDescription {
            get {
                return ResourceManager.GetString("MovieDetail_SneakPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneak preview.
        /// </summary>
        internal static string MovieDetail_SneakPreviewTitle {
            get {
                return ResourceManager.GetString("MovieDetail_SneakPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket &amp; Play Notifications.
        /// </summary>
        internal static string Notification_ChannelDescription {
            get {
                return ResourceManager.GetString("Notification_ChannelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The doors for {0} will close in 15 minutes! Make your way to hall {1} soon!.
        /// </summary>
        internal static string Notification_MovieStarting {
            get {
                return ResourceManager.GetString("Notification_MovieStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your movie is about to start!.
        /// </summary>
        internal static string Notification_MovieStartingTitle {
            get {
                return ResourceManager.GetString("Notification_MovieStartingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Fee.
        /// </summary>
        internal static string OrderOverview_3DFee {
            get {
                return ResourceManager.GetString("OrderOverview_3DFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount due.
        /// </summary>
        internal static string OrderOverview_AmountDue {
            get {
                return ResourceManager.GetString("OrderOverview_AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to tickets.
        /// </summary>
        internal static string OrderOverview_Back {
            get {
                return ResourceManager.GetString("OrderOverview_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In hall {0} at {1}.
        /// </summary>
        internal static string OrderOverview_Location {
            get {
                return ResourceManager.GetString("OrderOverview_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To payment.
        /// </summary>
        internal static string OrderOverview_Next {
            get {
                return ResourceManager.GetString("OrderOverview_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order overview.
        /// </summary>
        internal static string OrderOverview_Title {
            get {
                return ResourceManager.GetString("OrderOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string OrderOverview_Total {
            get {
                return ResourceManager.GetString("OrderOverview_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your seats:.
        /// </summary>
        internal static string OrderOverview_YourSeats {
            get {
                return ResourceManager.GetString("OrderOverview_YourSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string OrderTickets_3DYes {
            get {
                return ResourceManager.GetString("OrderTickets_3DYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To screenings.
        /// </summary>
        internal static string OrderTickets_Back {
            get {
                return ResourceManager.GetString("OrderTickets_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string OrderTickets_Child {
            get {
                return ResourceManager.GetString("OrderTickets_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        internal static string OrderTickets_Hall {
            get {
                return ResourceManager.GetString("OrderTickets_Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string OrderTickets_Movie {
            get {
                return ResourceManager.GetString("OrderTickets_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To payment.
        /// </summary>
        internal static string OrderTickets_Next {
            get {
                return ResourceManager.GetString("OrderTickets_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string OrderTickets_Regular {
            get {
                return ResourceManager.GetString("OrderTickets_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior.
        /// </summary>
        internal static string OrderTickets_Senior {
            get {
                return ResourceManager.GetString("OrderTickets_Senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string OrderTickets_Student {
            get {
                return ResourceManager.GetString("OrderTickets_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string OrderTickets_Time {
            get {
                return ResourceManager.GetString("OrderTickets_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your tickets.
        /// </summary>
        internal static string OrderTickets_Title {
            get {
                return ResourceManager.GetString("OrderTickets_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Bank --.
        /// </summary>
        internal static string Payment_BankPlaceholder {
            get {
                return ResourceManager.GetString("Payment_BankPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC/CID.
        /// </summary>
        internal static string Payment_CardFormCVC {
            get {
                return ResourceManager.GetString("Payment_CardFormCVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        internal static string Payment_CardFormExpiry {
            get {
                return ResourceManager.GetString("Payment_CardFormExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cardholder.
        /// </summary>
        internal static string Payment_CardFormName {
            get {
                return ResourceManager.GetString("Payment_CardFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number.
        /// </summary>
        internal static string Payment_CardFormNumber {
            get {
                return ResourceManager.GetString("Payment_CardFormNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with credit card.
        /// </summary>
        internal static string Payment_PayCreditCard {
            get {
                return ResourceManager.GetString("Payment_PayCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with iDeal/Wero.
        /// </summary>
        internal static string Payment_PayIdeal {
            get {
                return ResourceManager.GetString("Payment_PayIdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Payment_Required {
            get {
                return ResourceManager.GetString("Payment_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your bank.
        /// </summary>
        internal static string Payment_SelectBank {
            get {
                return ResourceManager.GetString("Payment_SelectBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment_Title {
            get {
                return ResourceManager.GetString("Payment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC/CIC is invalid.
        /// </summary>
        internal static string Payment_ValidateCvcInvalid {
            get {
                return ResourceManager.GetString("Payment_ValidateCvcInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC/CIC is required.
        /// </summary>
        internal static string Payment_ValidateCvcRequired {
            get {
                return ResourceManager.GetString("Payment_ValidateCvcRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card is expired.
        /// </summary>
        internal static string Payment_ValidateExpiryDue {
            get {
                return ResourceManager.GetString("Payment_ValidateExpiryDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry is required.
        /// </summary>
        internal static string Payment_ValidateExpiryRequired {
            get {
                return ResourceManager.GetString("Payment_ValidateExpiryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder name is required.
        /// </summary>
        internal static string Payment_ValidateNameRequired {
            get {
                return ResourceManager.GetString("Payment_ValidateNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is invalid.
        /// </summary>
        internal static string Payment_ValidateNumberInvalid {
            get {
                return ResourceManager.GetString("Payment_ValidateNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required.
        /// </summary>
        internal static string Payment_ValidateNumberRequired {
            get {
                return ResourceManager.GetString("Payment_ValidateNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster for {0}.
        /// </summary>
        internal static string PaymentSuccess_PosterAlt {
            get {
                return ResourceManager.GetString("PaymentSuccess_PosterAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print tickets.
        /// </summary>
        internal static string PaymentSuccess_PrintTickets {
            get {
                return ResourceManager.GetString("PaymentSuccess_PrintTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to download your tickets!.
        /// </summary>
        internal static string PaymentSuccess_RememberTickets {
            get {
                return ResourceManager.GetString("PaymentSuccess_RememberTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string PaymentSuccess_Share {
            get {
                return ResourceManager.GetString("PaymentSuccess_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on {0}.
        /// </summary>
        internal static string PaymentSuccess_ShareOn {
            get {
                return ResourceManager.GetString("PaymentSuccess_ShareOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        internal static string PaymentSuccess_Title {
            get {
                return ResourceManager.GetString("PaymentSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m going to see {0} on {1} at {2}!.
        /// </summary>
        internal static string Screening_ShareMessage {
            get {
                return ResourceManager.GetString("Screening_ShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SeatModal_Cancel {
            get {
                return ResourceManager.GetString("SeatModal_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change seats.
        /// </summary>
        internal static string SeatModal_ChangeSeats {
            get {
                return ResourceManager.GetString("SeatModal_ChangeSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string SeatModal_Confirm {
            get {
                return ResourceManager.GetString("SeatModal_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string SeatModal_LegendAvailable {
            get {
                return ResourceManager.GetString("SeatModal_LegendAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        internal static string SeatModal_LegendOccupied {
            get {
                return ResourceManager.GetString("SeatModal_LegendOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string SeatModal_LegendReserved {
            get {
                return ResourceManager.GetString("SeatModal_LegendReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string SeatModal_LegendSelected {
            get {
                return ResourceManager.GetString("SeatModal_LegendSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string SeatModal_Row {
            get {
                return ResourceManager.GetString("SeatModal_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        internal static string SeatModal_Screen {
            get {
                return ResourceManager.GetString("SeatModal_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat.
        /// </summary>
        internal static string SeatModal_Seat {
            get {
                return ResourceManager.GetString("SeatModal_Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No seats chosen.
        /// </summary>
        internal static string SeatModal_SummaryEmpty {
            get {
                return ResourceManager.GetString("SeatModal_SummaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected:.
        /// </summary>
        internal static string SeatModal_SummarySelected {
            get {
                return ResourceManager.GetString("SeatModal_SummarySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected seats.
        /// </summary>
        internal static string SeatModal_SummaryTitle {
            get {
                return ResourceManager.GetString("SeatModal_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your seats.
        /// </summary>
        internal static string SeatModal_Title {
            get {
                return ResourceManager.GetString("SeatModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheelchair.
        /// </summary>
        internal static string SeatModal_Wheelchair {
            get {
                return ResourceManager.GetString("SeatModal_Wheelchair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t find your order. Try again later?.
        /// </summary>
        internal static string TicketDetail_ErrorDescription {
            get {
                return ResourceManager.GetString("TicketDetail_ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found....
        /// </summary>
        internal static string TicketDetail_ErrorTitle {
            get {
                return ResourceManager.GetString("TicketDetail_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this to the attendant at the door!.
        /// </summary>
        internal static string TicketDetail_QrCodeInstruction {
            get {
                return ResourceManager.GetString("TicketDetail_QrCodeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order.
        /// </summary>
        internal static string TicketDetail_Title {
            get {
                return ResourceManager.GetString("TicketDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Tickets_Header {
            get {
                return ResourceManager.GetString("Tickets_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall {0} at {1}.
        /// </summary>
        internal static string Tickets_ScreeningLocation {
            get {
                return ResourceManager.GetString("Tickets_ScreeningLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings.
        /// </summary>
        internal static string You_Header {
            get {
                return ResourceManager.GetString("You_Header", resourceCulture);
            }
        }
    }
}
